#!/bin/bash
GroupOU="ou=Grupos"
DbFILE="/usr/local/samba/private/sam.ldb"
Domain="__BASEDC__"
SAMDOM="__SAMDOM__"

if [ -z $1 ]
then
	echo "$0 <nome do grupo>"
else
	GE=`/usr/local/samba/bin/ldbsearch -H $DbFILE -b $GroupOU,$Domain cn=$1 | egrep ^cn | wc -l`
	if [ $GE -ne 1 ]
	then
		LastGID=`/usr/local/samba/bin/ldbsearch -H $DbFILE -b $GroupOU,$Domain  gidnumber | egrep gid | awk '{ print $ 2 }' | sort -n | tail -1`
		if [ -z $LastGID ]
		then
			LastGID=5000
		fi
		NextGID=$((${LastGID}+1))
		samba-tool group add $1 --groupou=$GroupOU --nis-domain=$SAMDOM --gid-number=${NextGID}
	else
		echo "$1 já existe"
	fi
fi
